version: "3.4"

services:
  database:
    image: postgis/postgis:${POSTGRES_VERSION:-15}-${POSTGIS_VERSION:-3.3}-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-app}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-!ChangeMe!}
      - POSTGRES_USER=${POSTGRES_USER:-app}
#    ports:
#      - "5432:5432"
    volumes:
      - ${POSTGRES_DATA_DIR}:/var/lib/postgresql/data
      - pg_socket:/var/run/postgresql
  php:
    build:
      context: ./api
      target: app_php
    depends_on:
      - database
    restart: unless-stopped
    volumes:
      - ./api:/srv/api
      - php_socket:/var/run/php
      - pg_socket:/var/run/postgresql
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
#    environment:
#      DATABASE_URL: postgresql://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-!ChangeMe!}@database:5432/${POSTGRES_DB:-app}?serverVersion=${POSTGRES_VERSION:-15}
#      TRUSTED_PROXIES: ${TRUSTED_PROXIES:-127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16}
#      TRUSTED_HOSTS: ^${SERVER_NAME:-example\.com|localhost}|caddy$$
  nginx:
    image: nginx:1.25-alpine
    depends_on:
      - php
    ports:
      - "${NGINX_PORT:-8000}:80"
    volumes:
      - "${WWW_CLIENT_DIR}:/srv/client:ro"
      - ./api:/srv/api
      - ./api/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./api/docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - php_socket:/var/run/php
    environment:
      - NGINX_HOST=${NGINX_HOST:-localhost}
    logging:
      driver: local
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  php_socket:
  pg_socket:
