api_platform:
    title: ERC MEDGREENREV Project API Platform
    version: 1.0.0
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
    mapping:
        paths:
            - '%kernel.project_dir%/config/api_platform/resources'
    formats:
        jsonld: [ 'application/ld+json' ]
        jsonapi:  ['application/vnd.api+json']
    defaults:
        pagination_client_items_per_page: true
