api_platform:
    title: ERC Project API Platform
    version: 1.0.0
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
    mapping:
        paths:
            - '%kernel.project_dir%/config/api_platform/resources'
