doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver: pdo_pgsql
                dbname: app
                server_version: 15
                user: app
                host: null
                ## Socket connection
                schema_filter: ~^(?!(tiger\.|topology\.|vw_))~

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '15'
    orm:
        auto_generate_proxy_classes: true
        default_entity_manager: default
        enable_lazy_ghost_objects: true
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: true
                mappings:
                    App:
                        is_bundle: false
                        type: xml
                        dir: '%kernel.project_dir%/config/mapping/orm'
                        prefix: 'App\Entity'
                        alias: App
                dql:
                    string_functions:
                        cast: Oro\ORM\Query\AST\Functions\Cast
when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            #            dbname_suffix: '_test%env(default::TEST_TOKEN)%'
            dbname_suffix: '_test%env(default:default_test_worker:TEST_WORKER)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
