services:
    Jsor\Doctrine\PostGIS\Event\ORMSchemaDoctrineListener:
        tags: [{ name: doctrine.listener, connection: default }]

doctrine:
    dbal:
        mapping_types:
            _text: string
        types:
            geometry: 'Jsor\Doctrine\PostGIS\Types\GeometryType'
    orm:
        dql:
            string_functions:
                ST_AsGeoJSON: 'Jsor\Doctrine\PostGIS\Functions\ST_AsGeoJSON'
                ST_GeomFromGeoJSON: 'Jsor\Doctrine\PostGIS\Functions\ST_GeomFromGeoJSON'
