vich_uploader:
    db_driver: orm
    
    mappings:
        media_object:
            uri_prefix: /media
            upload_destination: /srv/static
            namer: App\Service\MediaObjectFileHashNamer
            directory_namer:
                service: Vich\UploaderBundle\Naming\SubdirDirectoryNamer
                options: { chars_per_dir: 1, dirs: 2 }
            
